### ISSUE TITLE
SSML error ?

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/skill_Speller#1]
I get the following each time i go to use speller skill. Using Amazon tts 

>[ASRManager]              Asr captured: how do you spell cat
[AudioManager]            Playing wav stream using upmix audio output from site id Alice (channels: 1, rate: 16000)
[MqttManager]             Using probability threshold of 0.5
[SkillManager]            The intent "DoSpellWord" was consumed by Speller
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 3428, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 1782, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 1177, in loop
    rc = self.loop_read(max_packets)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 1568, in loop_read
    rc = self._packet_read()
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 2315, in _packet_read
    rc = self._packet_handle()
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 2952, in _packet_handle
    return self._handle_publish()
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 3228, in _handle_publish
    self._handle_on_message(message)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 3416, in _handle_on_message
    callback(self, self._userdata, message)
  File "/home/pi/ProjectAlice/core/server/MqttManager.py", line 466, in intentSay
    self.broadcast(method=constants.EVENT_SAY, exceptions=[self.name], propagateToSkills=True, session=session)
  File "/home/pi/ProjectAlice/core/base/model/ProjectAliceObject.py", line 79, in broadcast
    func(**kwargs)
  File "/home/pi/ProjectAlice/core/voice/TTSManager.py", line 131, in onSay
    self._tts.onSay(session)
  File "/home/pi/ProjectAlice/core/voice/model/AmazonTts.py", line 283, in onSay
    VoiceId=self._voice.title()
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidSsmlException: An error occurred (InvalidSsmlException) when calling the SynthesizeSpeech operation: Unsupported SSML feature used

**Comment by Psychokiller1888** [comment]
Ok, I got it...

https://developer.amazon.com/en-US/docs/alexa/custom-skills/speechcon-reference-interjections-english-us.html

say-as interjection is US only
